name: Deploy Assets to WordPress.org
on:
  push:
    branches:
    - main
jobs:
  trunk:
    name: Deploy Assets
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        ASSETS_DIR: .wordpress-org
        IGNORE_OTHER_FILES: true
